services: 
    uwsgi-nginx-flask:
        command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 main.py runserver 0.0.0.0:8000 --nothreading --noreload"]
        ports:
            - 5678:5678